name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Agrega tus variables de entorno aquí, por ejemplo:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  APP_ID: ${{ secrets.APP_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.10.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK

        run: flutter build apk --split-per-abi

      - name: Distribute APK via Firebase App Distribution

        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.APP_ID }}
          token: ${{ env.FIREBASE_TOKEN }}
          apkPath: "build/app/outputs/apk/release/app-arm64-v8a-release.apk"
