name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Agrega tus variables de entorno aquí, por ejemplo:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  APP_ID: ${{ secrets.APP_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
        

      - name: Install dependencies
        run: flutter pub get

# build release aab
      - name: Build release aab
        run: flutter build appbundle --release --no-shrink

# save the build in the artifacts
      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

# upload the build to firebase app distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.APP_ID }}
          token: ${{ env.FIREBASE_TOKEN }}
          releaseNotes: "Release notes"
          groups: "testers"
          file: "build/app/outputs/bundle/release/app-release.aab"

