name: Flutter android and iOS deploy

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    name: Build and deploy apk and ipa release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"

    - run: flutter pub get
  
    - run: flutter build apk
  



      
