name: Flutter iOS build

on:
  push:
    branches: [ main_ios ]
    tags: [ v* ]

jobs:


  build_ios:
    name: Build Flutter (iOS)
  
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Upload ipa
        uses: actions/upload-artifact@v3
        with:
          name: IOS_IPA
          path: /Users/runner/work/pacman_flutter/pacman_flutter/build/ios/iphoneos/Runner.app

