name: Build and Distribute Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: packman-battle
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
    

    - name: Install Firebase CLI
      run: curl -sL firebase.tools | bash
      env:
        PATH: $PATH:/root/.npm-global/bin

    - name: Authenticate with Firebase
      run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

    - name: Distribute App Bundle via Firebase App Distribution
      run: firebase appdistribution:distribute "build/app/outputs/bundle/release/app-release.aab" --app ${{ env.APP_NAME }} --groups "internal" --release-notes-file "release_notes.txt"
