name: Flutter android build

on:
  push:
    branches: [ main_android ]
    tags: [ v* ]

jobs:

  build_appbundle:
    name: Build Flutter (Android)
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Generate key.properties file
        run: |
            echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
            echo "keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
            echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
            
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle --release
      - name: Upload appbundle to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ANDROID_APPBUNDLE
          path: /build/app/outputs/bundle/release/app.aab

  



      
