name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Build and deploy Android app
        run: |
          cd my-app/
          flutter build apk
          firebase appdistribution:distribute my-app/build/app/outputs/flutter-apk/app-release.apk --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
